### ISSUE TITLE
[BUG] Unable to write correct xlsx file.

### ISSUE THREAD

**Issue by Freymaurer** [fslaborg/FsSpreadsheet#49]
Not sure if this is an error in usage or execution.

```fsharp
#r "nuget: FsSpreadsheet, 3.1.1"
#r "nuget: FsSpreadsheet.ExcelIO, 3.1.1"

let path = @"C:/Users/Kevin/Desktop/Book1.xlsx"

open FsSpreadsheet
open FsSpreadsheet.ExcelIO

let wb = new FsWorkbook()

let ws = wb.InitWorksheet("New Worksheet")

ws.AddCell(FsCell("My Column 1",address=FsAddress("B1")))
ws.AddCell(FsCell("My Column 2",address=FsAddress("C1")))
let t = FsTable("My New Table", FsRangeAddress("B1:C2"))

ws.AddTable(t)

wb.ToFile(path)
```

-------------->
![image](https://github.com/CSBiology/FsSpreadsheet/assets/39732517/36498400-78e2-4a32-8aea-64e032d3b665)
![image](https://github.com/CSBiology/FsSpreadsheet/assets/39732517/bf6bac80-6092-4704-a538-28019d682660)

**Comment by HLWeil** [comment]
This happens because the `TableColumns` field in the xlsx file is empty. 
![image](https://github.com/CSBiology/FsSpreadsheet/assets/17880410/1b28e532-72c0-4b75-bf76-f15e2420bd5a)

This is because no `TableFields` are set in the table object. Theoretically this could be done when adding the table to the worksheet. Here it could be checked whether the cellcollection in the worksheet does contain cell values in the header row of the specified table range.

**Comment by HLWeil** [comment]
Alternatively, this step could be performed when writing the table.

**Comment by Freymaurer** [comment]
Propably fixed and outdated, will close
